version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: ordexa_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ordexa
      POSTGRES_USER: ordexa_user
      POSTGRES_PASSWORD: ordexa_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
