/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersCreateRouteImport } from './routes/orders/create'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'

const OrdersCreateRoute = OrdersCreateRouteImport.update({
  id: '/orders/create',
  path: '/orders/create',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
}
export interface FileRoutesByTo {
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/create': typeof OrdersCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/orders/$orderId' | '/orders/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/orders/$orderId' | '/orders/create'
  id: '__root__' | '/orders/$orderId' | '/orders/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersCreateRoute: typeof OrdersCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders/create': {
      id: '/orders/create'
      path: '/orders/create'
      fullPath: '/orders/create'
      preLoaderRoute: typeof OrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersCreateRoute: OrdersCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
