name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start frontend (Vite)
        run: bun run dev &
        working-directory: apps/frontend

      - name: Wait for frontend to be ready
        run: |
          npx wait-on http://localhost:5173

      - name: Run E2E tests
        run: npx playwright test apps/e2e
